using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Mediator.Generator;

[Generator(LanguageNames.CSharp)]
public class SourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var handlerDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => s is ClassDeclarationSyntax { BaseList: not null },
                transform: static (ctx, _) => GetSemanticTarget(ctx))
            .Where(static m => m is not null);

        var collectedHandlers = handlerDeclarations.Collect();

        context.RegisterSourceOutput(collectedHandlers,
            static (spc, handlers) => Execute(spc, handlers));
    }

    private static INamedTypeSymbol? GetSemanticTarget(GeneratorSyntaxContext ctx)
    {
        var classSymbol = ctx.SemanticModel.GetDeclaredSymbol((ClassDeclarationSyntax)ctx.Node) as INamedTypeSymbol;

        return classSymbol != null && classSymbol.AllInterfaces.Any(i => i.Name == "IRequestHandler")
            ? classSymbol
            : null;
    }

    private static void Execute(SourceProductionContext context, ImmutableArray<INamedTypeSymbol?> handlers)
    {
        CreateMediator(context, handlers);
        CreateExtensionMethod(context, handlers);
    }

    private static void CreateExtensionMethod(SourceProductionContext context,
        ImmutableArray<INamedTypeSymbol?> handlers)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine("namespace Mediator.Generated;");
        sb.AppendLine();
        sb.AppendLine("public static class MediatorExtensions");
        sb.AppendLine("{");
        sb.AppendLine("     extension(IServiceCollection services)");
        sb.AppendLine("     {");
        sb.AppendLine("         public void AddSingletonMediatorServices()");
        sb.AppendLine("         {");
        sb.AppendLine("             services.AddSingleton<global::Mediator.Contract.IMediator, SourceMediator>();");
        if (!handlers.IsDefaultOrEmpty)
        {
            foreach (var handler in handlers)
            {
                if (handler == null) continue;

                var interfaceSymbol = handler.AllInterfaces.FirstOrDefault(i =>
                    i.Name == "IRequestHandler" &&
                    i.ContainingNamespace.ToDisplayString().Contains("Mediator.Contract"));

                if (interfaceSymbol == null || interfaceSymbol.TypeArguments.Length != 2) continue;

                var requestType = interfaceSymbol.TypeArguments[0]
                    .ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                var responseType = interfaceSymbol.TypeArguments[1]
                    .ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                var handlerType = handler.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

                sb.AppendLine(
                    $"             services.AddSingleton<global::Mediator.Contract.IRequestHandler<{requestType}, {responseType}>, {handlerType}>();");
            }
        }

        sb.AppendLine("         }");
        sb.AppendLine("     }");
        sb.AppendLine("}");

        context.AddSource("MediatorExtensions.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void CreateMediator(SourceProductionContext context, ImmutableArray<INamedTypeSymbol?> handlers)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine("namespace Mediator.Generated;");
        sb.AppendLine();
        sb.AppendLine("public class SourceMediator : global::Mediator.Contract.IMediator");
        sb.AppendLine("{");
        sb.AppendLine(
            "    private readonly Dictionary<Type, Func<object, CancellationToken, Task<object>>> _handlers = new();");
        sb.AppendLine("    private readonly IServiceProvider _serviceProvider;");
        sb.AppendLine();
        sb.AppendLine($"    public SourceMediator(IServiceProvider serviceProvider)");
        sb.AppendLine("    {");
        sb.AppendLine("        _serviceProvider = serviceProvider;");
        sb.AppendLine("        RegisterHandlers();");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    private void RegisterHandlers()");
        sb.AppendLine("    {");

        if (!handlers.IsDefaultOrEmpty)
        {
            foreach (var handler in handlers)
            {
                if (handler == null) continue;

                var interfaceSymbol = handler.AllInterfaces.FirstOrDefault(i =>
                    i.Name == "IRequestHandler" &&
                    i.ContainingNamespace.ToDisplayString().Contains("Mediator.Contract"));

                if (interfaceSymbol == null || interfaceSymbol.TypeArguments.Length != 2) continue;

                var requestType = interfaceSymbol.TypeArguments[0]
                    .ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                var handlerType = handler.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

                sb.AppendLine($"        _handlers.Add(typeof({requestType}), async (req, ct) =>");
                sb.AppendLine("        {");
                sb.AppendLine(
                    $"            var handler = (_serviceProvider.GetService(typeof({handlerType})) as {handlerType})");
                sb.AppendLine(
                    $"                          ?? ActivatorUtilities.CreateInstance<{handlerType}>(_serviceProvider);");
                sb.AppendLine($"            var result = await handler.HandleAsync(({requestType})req);");
                sb.AppendLine("            return (object)result;");
                sb.AppendLine("        });");

                if (!SymbolEqualityComparer.Default.Equals(handler, handlers.Last()))
                {
                    sb.AppendLine();
                }
            }
        }

        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine(
            "    public async Task<TResponse> HandleAsync<TResponse>(global::Mediator.Contract.IRequest<TResponse> request, CancellationToken ct = default)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (!_handlers.TryGetValue(request.GetType(), out var handlerWrapper))");
        sb.AppendLine("            throw new Exception($\"Handler for type {request.GetType()} not found\");");
        sb.AppendLine();
        sb.AppendLine("        return (TResponse)await handlerWrapper(request, ct);");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("SourceMediator.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}