using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Framework.Generator.Mediator;

[Generator(LanguageNames.CSharp)]
public class MediatorSourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var handlerDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => s is ClassDeclarationSyntax { BaseList: not null },
                transform: static (ctx, _) => GetSemanticTarget(ctx))
            .Where(static m => m is not null);

        var collectedHandlers = handlerDeclarations.Collect();

        context.RegisterSourceOutput(collectedHandlers,
            static (spc, handlers) => Execute(spc, handlers));
    }

    private static INamedTypeSymbol? GetSemanticTarget(GeneratorSyntaxContext ctx)
    {
        var classSymbol = ctx.SemanticModel.GetDeclaredSymbol((ClassDeclarationSyntax)ctx.Node) as INamedTypeSymbol;

        if (classSymbol != null && classSymbol.AllInterfaces.Any(i => i.Name == "IRequestHandler"))
        {
            return classSymbol;
        }

        return null;
    }

    private static void Execute(SourceProductionContext context, ImmutableArray<INamedTypeSymbol?> handlers)
    {
        if (handlers.IsDefaultOrEmpty) return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Framework.Tools.Contract;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine("namespace Framework.Tools.Implementation;");
        sb.AppendLine();
        sb.AppendLine("public partial class Mediator");
        sb.AppendLine("{");
        sb.AppendLine("    partial void RegisterHandlers()");
        sb.AppendLine("    {");

        foreach (var handler in handlers)
        {
            if (handler == null) continue;

            var interfaceSymbol = handler.AllInterfaces.FirstOrDefault(i => i.Name == "IRequestHandler");

            if (interfaceSymbol is { TypeArguments.Length: 2 })
            {
                var requestType = interfaceSymbol.TypeArguments[0].ToDisplayString();
                var handlerType = handler.ToDisplayString();

                sb.AppendLine($"        _handlers.Add(typeof({requestType}), async (req, ct) =>");
                sb.AppendLine("        {");
                sb.AppendLine(
                    $"            var handler = (_serviceProvider.GetService(typeof({handlerType})) as {handlerType}) ");
                sb.AppendLine(
                    $"                          ?? ActivatorUtilities.CreateInstance<{handlerType}>(_serviceProvider);");
                sb.AppendLine($"            var result = await handler.HandleAsync(({requestType})req);");
                sb.AppendLine("            return (object)result;");
                sb.AppendLine("        });");
            }
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("Mediator.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}