using Framework.Tools.Contract;
using Framework.Tools.Exceptions;

namespace Framework.Tools.Implementation;

//Do not "fix" anything here.
//The variables and modifiers are highlighted because the partial class is autogenerated 
public partial class Mediator : IMediator
{
    private readonly Dictionary<Type, Func<object, CancellationToken, Task<object>>> _handlers = new();
    private readonly IServiceProvider _serviceProvider;

    public Mediator(IServiceProvider serviceProvider)
    {
        _serviceProvider = serviceProvider;
        RegisterHandlers();
    }

    partial void RegisterHandlers();

    public async Task<TResponse> HandleAsync<TResponse>(IRequest<TResponse> request, CancellationToken ct = default)
    {
        if (!_handlers.TryGetValue(request.GetType(), out var handlerWrapper))
            throw new MediatorException($"Handler for type {request.GetType()} not found");

        return (TResponse)await handlerWrapper(request, ct);
    }
}